apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobdemo
  labels:
    app: jobdemo
spec:
  selector:
    matchLabels:
      app: jobdemo
  template:
    metadata:
      labels:
        app: jobdemo
    spec:
      containers:
        - name: jobdemo
          image: deccr.ccs.tencentyun.com/myfana2022/backend:f9b17b93077506178a70326d2735dc54ccd21acb
          ports:
            - containerPort: 8080
          env:
            - name: GREETING_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: spring-boot-configmaps-demo
                  key: greeter.prefix

