apiVersion: v1
kind: Service
metadata:
  name: jobdemo
  labels:
    app: jobdemo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: jobdemo
  type: LoadBalancer
